version: "3"

volumes:
  nextcloud-data:
  db:

services:
  db:
    image: mysql:8.0.23
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - /tmp/nextcloud.sql:/docker-entrypoint-initdb.d/nextcloud.sql
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=badPass1!
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=16d55469ac05472c96220105b6e4976f

  app:
    image: nextcloud:19.0.10-apache
    restart: always
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - nextcloud-data:/var/www/html
    environment:
      - NEXTCLOUD_ADMIN_USER=admin_9822
      - NEXTCLOUD_ADMIN_PASSWORD=badPass1!
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=16d55469ac05472c96220105b6e4976f
      - MYSQL_HOST=db
