version: "3"
  
networks:
  frontend:
    name: ngx-fe
    driver: bridge
  backend:
    name: ngx-be
    driver: bridge

volumes:
  nextcloud-data:
  db:

services:
  lb:
    build: ./nginx
    restart: always
    links:
      - app:nextcloud
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/index.html:/data/up1/index.html
    networks:
      frontend:
    ports:
      - 80:80
    depends_on:
      - db
      - app

  db:
    image: mysql:8.0.23
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - /tmp/nextcloud.sql:/docker-entrypoint-initdb.d/nextcloud.sql
      - db:/var/lib/mysql
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=badPass1!
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=16d55469ac05472c96220105b6e4976f

  app:
    image: nextcloud:19.0.10-apache
    restart: always
    links:
      - db
    volumes:
      - nextcloud-data:/var/www/html
    networks:
      frontend:
      backend:
    environment:
      - NEXTCLOUD_ADMIN_USER=admin_9822
      - NEXTCLOUD_ADMIN_PASSWORD=badPass1!
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=16d55469ac05472c96220105b6e4976f
      - MYSQL_HOST=db
    depends_on:
      - db
