---
version: "3"
networks:
  frontend:
    name: ngx-fe
    driver: bridge
  backend:
    name: ngx-be
    driver: bridge

volumes:
  nextcloud-data:
  db:
  certs:

services:
  lb:
    image: nginx:1.19.10
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      frontend:
    ports:
      - 8080:80
      - 8443:443
    depends_on:
      - db
      - app
    volumes_from:
      - app
    user: 1001:101

  db:
    image: mysql:8.0.23
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - ./mysql/nextcloud.sql:/docker-entrypoint-initdb.d/nextcloud.sql
      - db:/var/lib/mysql
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=badPass1!
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=16d55469ac05472c96220105b6e4976f
    cap_add:
      - SYS_NICE

  app:
    image: nextcloud:19.0.10-fpm
    restart: always
    volumes:
      - nextcloud-data:/var/www/html/
      - certs:/certs
    networks:
      frontend:
      backend:
    environment:
      - NEXTCLOUD_ADMIN_USER=admin_9822
      - NEXTCLOUD_ADMIN_PASSWORD=badPass1!
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=16d55469ac05472c96220105b6e4976f
      - MYSQL_HOST=db
    depends_on:
      - db
    user: 1001:101
